#!/usr/bin/env python3

from google.protobuf.compiler.plugin_pb2 import CodeGeneratorResponse
from google.protobuf.descriptor_pb2 import \
    FileDescriptorProto, \
    EnumDescriptorProto, DescriptorProto, \
    ServiceDescriptorProto, MethodDescriptorProto

from generator import Generator

class KMMGrpcAndroidGenerator(Generator):
    def __init__(self):
        super().__init__(baseName="kmm-grpc-android")
    
    def getOutputFileName(self, protoFileName: str, packageName: str) -> str:
        return self.typeNameCase(packageName) + "GrpcAndroidClient.kt"

    def processMessagesAndEnums(self, protoFile: FileDescriptorProto,
                                response: CodeGeneratorResponse):
        pass

    def getHeader(self, protoFile: FileDescriptorProto) -> list[str]:
        pkg = self.options["java_package"]
        importFlow = "import kotlinx.coroutines.flow."
        lines = [
            "package " + pkg,
            "",
            importFlow + "Flow",
            importFlow + "map",
        ]
        for service in protoFile.service:
            # Not sure if service.name is the whole story, but it should be
            # an easy fix if not.
            lines.append("import %s.%sGrpcKt.%sCoroutineStub" % \
                    (pkg, service.name, service.name))
        return lines + [""]
    
    def getFooter(self, protoFile: FileDescriptorProto) -> list[str]:
        return [""]
    
    def getServiceHeader(self, protoFile: FileDescriptorProto,
                         serv: ServiceDescriptorProto) -> list[str]:
        lines = super().getServiceHeader(protoFile, serv)
        serviceName = self.getServiceName(protoFile, serv)
        lines.extend([
            "    private val stub: %sCoroutineStub" % serv.name,
            "): %sGrpcClient {" % serviceName,
        ])
        return lines

    def getServiceFooter(self, protoFile: FileDescriptorProto,
                         serv: ServiceDescriptorProto,
                         indentationLevel: int) -> list[str]:
        return ["}"]

    def getServiceMethod(self, protoFile: FileDescriptorProto,
                        serv: ServiceDescriptorProto,
                        method: MethodDescriptorProto) -> list[str]:
        indentationLevel += 1
        lines = self.getMethodSignature(protoFile,
                                        serv,
                                        method,
                                        indentationLevel)
        indent = "    "
        lines[0] = indent + "override " + lines[0][4:]
        lines[-1] += " ="
        methodName = self.memberCase(method.name)
        if method.client_streaming:
            input = "map { it.toProto() }"
        else:
            input = "toProto()"
        if method.server_streaming:
            output = "map { it.toData() }"
        else:
            output = "toData()"
        lines.extend([
            indent + "    stub.%s(request.%s).%s" % \
                (methodName, input, output),
            ""
        ])
        return lines

    def getClientVariety(self):
        return "AndroidClient"
    
    def getServiceOpenBracket(self):
        return "("


def main():
    generator = KMMGrpcAndroidGenerator()
    generator.runOnStdinAndStdout()

if __name__ == "__main__":
    main()
