#!/usr/bin/env python3

from google.protobuf.compiler.plugin_pb2 import CodeGeneratorResponse
from google.protobuf.descriptor_pb2 import \
    FileDescriptorProto, \
    ServiceDescriptorProto, MethodDescriptorProto

from generator import Generator

class KMMGrpcSharedGenerator(Generator):
    def __init__(self):
        super().__init__(baseName="kmm-grpc-shared")
    
    def processMessagesAndEnums(self, protoFile: FileDescriptorProto,
                                response: CodeGeneratorResponse):
        pass

    def getOutputFileName(self, protoFileName: str, packageName: str) -> str:
        return self.typeNameCase(packageName) + "GrpcClient.kt"

    def getHeader(self, protoFile: FileDescriptorProto) -> list[str]:
        return [
            "package " + self.options["java_package"],
            "",
            "import kotlinx.coroutines.flow.Flow",
            "",
        ]
    
    def getFooter(self, protoFile: FileDescriptorProto) -> list[str]:
        return [""]
    
    def getServiceHeader(self, protoFile: FileDescriptorProto,
                         serv: ServiceDescriptorProto,
                         indentationLevel: int) -> list[str]:
        serviceName = self.getServiceName(protoFile, serv)
        return [
            "@ObjcName(swiftName = %sKMMGrpcClient)" % serviceName,
            "interface %sGrpcClient {" % serviceName
        ]

    def getServiceEntity(self):
        ''' "class", "interface" etc for a service definition. '''
        return "interface"
    
    def getServiceFooter(self, protoFile: FileDescriptorProto,
                         serv: ServiceDescriptorProto,
                         indentationLevel: int) -> list[str]:
        return ["}"]

    def getServiceMethod(self, protoFile: FileDescriptorProto,
                        serv: ServiceDescriptorProto,
                        method: MethodDescriptorProto,
                        indentationLevel: int) -> list[str]:
        return self.getMethodSignature(protoFile,
                                        serv,
                                        method,
                                        indentationLevel) + [""]
    
    def getRole(self):
        return "GrpcClient"


def main():
    generator = KMMGrpcSharedGenerator()
    generator.runOnStdinAndStdout()

if __name__ == "__main__":
    main()
